services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGODB_URL=mongodb://mongo:27017/myDatabase
      - REDIS_URL=redis://redis:6379
      - ORIGIN_URL=3000
      - ADMIN_SETUP_KEY=your_secure_random_string_here
      - ACTIVATION_SECRET=2348328292
      - ACCESS_TOKEN_SECRET=/7?r8FJ34tvmdmhNx6L%&VW6k1MMqux2dbA/IbiiOL
      - REFRESH_TOKEN_SECRET=F48QU\£aLP%mJb|SBfL$<uev>$JD\_dcot0/+ILK.@
      - ACCESS_TOKEN_EXPIRE=8m
      - REFRESH_TOKEN_EXPIRE=4m
      - CLOUD_NAME=dmfgl8jgi
      - API_KEY=871975384676272
      - API_SECRET=6tpIpwqGcS-2pv3z3KMX7fhA7eA
      - CLOUDINARY_URL=cloudinary://871975384676272:6tpIpwqGcS-2pv3z3KMX7fhA7eA@dmfgl8jgi
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SERVICE=gmail
      - SMTP_MAIL=waqarahmed44870@gmail.com
      - SMTP_PASSWORD=owbhikaupzlmvurr
      - STRIPE_SECRET_KEY=sk_test_4eCk2jJ6v0x1q3z2g5f8Q6JX
      - STRIPE_PUBLISHABLE_KEY=pk_test_51N1v2aSByxk0X3g5f8Q6JX
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data: